name: My First Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: first-step
          run:
            echo "This is my first job"
        - name: List Files
          run:
            ls
        - name: read files
          run:
            cat README.md



